import type { Metadata } from "next"
import localFont from "next/font/local"

import "./globals.css"

const InstrumentSansReg = localFont({
  src: "./fonts/static/InstrumentSans-Regular.ttf",
  variable: "--font-instrument-sans-regular",
  weight: "400",
})
const InstrumentSansBold = localFont({
  src: "./fonts/static/InstrumentSans-Bold.ttf",
  variable: "--font-instrument-sans-bold",
  weight: "700",
})
const InstrumentSansSemiBold = localFont({
  src: "./fonts/static/InstrumentSans-SemiBold.ttf",
  variable: "--font-instrument-sans-semibold",
  weight: "600",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${InstrumentSansReg.variable} ${InstrumentSansBold.variable} ${InstrumentSansSemiBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
